import Vue from "vue";
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faUserSecret,
  faUser,
  faBell,
  faHome,
  faUsers,
  faUserFriends,
  faUsersCog,
  faEllipsisV,
  faArrowRight,
  faArrowLeft,
  faDog,
  faBars,
  faBullhorn,
  faIdCard,
  faStar,
  faUserCog,
  faTag,
  faDollarSign,
  faFileAlt,
  faWallet,
  faUserPlus,
  faSignOutAlt,
  faUndo,
  faFileInvoiceDollar,
  faCogs,
  faPaw,
  faQuestion,
  faLayerGroup,
  faSearch,
  faAngleDown,
  faAngleRight,
  faExclamationCircle,
  faExclamationTriangle,
  faGift,
  faLightbulb,
  faHeadphones,
  faVenus,
  faMars,
  faVideo,
  faCalendarDay,
  faHeart,
  faEnvelope,
  faCheckCircle,
  faCheck,
  faSpinner,
  faCaretDown,
  faCaretUp,
  faCameraRetro,
  faCaretRight,
  faTimes,
  faComment,
  faSyncAlt
} from "@fortawesome/free-solid-svg-icons";

import {
  faFacebook,
  faTwitter,
  faLinkedin,
  faYoutube
} from "@fortawesome/free-brands-svg-icons";

import {
  faHeart as farHeart,
  faMeh,
  faStar as farStar
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faUserSecret,
  faUser,
  faBell,
  faHome,
  faUsers,
  faUserFriends,
  faUsersCog,
  faEllipsisV,
  faArrowRight,
  faArrowLeft,
  faDog,
  faBars,
  faBullhorn,
  faIdCard,
  faStar,
  faUserCog,
  faTag,
  faDollarSign,
  faFileAlt,
  faWallet,
  faUserPlus,
  faSignOutAlt,
  faUndo,
  faFileInvoiceDollar,
  faCogs,
  faPaw,
  faQuestion,
  faLayerGroup,
  faSearch,
  farHeart,
  faAngleDown,
  faAngleRight,
  faExclamationCircle,
  faGift,
  faLightbulb,
  faHeadphones,
  faFacebook,
  faTwitter,
  faLinkedin,
  faYoutube,
  faVenus,
  faMars,
  faVideo,
  faCalendarDay,
  faHeart,
  faMeh,
  faEnvelope,
  farStar,
  faCheckCircle,
  faSpinner,
  faCaretDown,
  faCaretUp,
  faCameraRetro,
  faCaretRight,
  faTimes,
  faComment,
  faSyncAlt,
  faCheck,
  faExclamationTriangle
);
Vue.component("font-awesome-icon", FontAwesomeIcon);
